### PR TITLE
Lab#1

### PR DESCRIPTION
**Pull request by michaelGRU**
@oliviatessa

### CODE REVIEW

**Comment by oliviatessa** [comment]
@michaelGRU Still having trouble rendering in the html preview application. I'm going to try to open it from my computer and I'll get back to you.

**Comment by michaelGRU** [comment]
It works fine on my computer. I'm using https://htmlpreview.github.io/. I just copy and paste the url

**Comment by oliviatessa** [comment]
Yeah that’s what I was using to. It wasn’t rendering correctly, but I’ve pulled it and can see it now! Thanks!

**Comment by oliviatessa** [comment]
Awesome job, Michael! 

Comments on lab 1: 
- For your first sigma calculation for the chi-squared distribution, all the math is correct, but what is the significance of the sigma value? You say a sigma of 1.485 corresponds to 93.1%. Really, 93.1% corresponds to a z-score of 1.485. Sigma is normally interpreted as 1 - probability associated with z score. Meaning, if you say your sigma is 1.485, I know you have a (100 - 93.1) 6.9% of your background giving you a false positive signal. 
- Don't forget to describe the background distribution. For the Poisson distribution, what parameter(s) does it depend on? 

Good work!

**Pull request closed without merging**
